version: '3.7'
services:
  rabbit:
    image: "rabbitmq:3.6.6-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    restart: always
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    hostname: nginx-1
    image: nginx:stable-alpine
    ports:
      - '3333:9080'
    volumes:
      - ./app:/var/www/html/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  mailhog:
    container_name: programwithgio-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
  gotify:
    image: gotify/server
    hostname: gotify-1
    ports:
      - "2080:2080"
    volumes:
      - ./gotify-dc/data:/app/data
      - ./gotify/config.yml:/etc/gotify/config.yml
    restart: unless-stopped
    environment:
      - GOTIFY_SERVER_PORT=2080
      - GOTIFY_DEFAULTUSER_NAME=user
      - GOTIFY_DEFAULTUSER_PASS=pass



