doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Verification:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Verification/Infrastructure/DoctrineMapping'
                prefix: 'App\Verification\Domain\Entity'
                alias: Verification
            Notification:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Notification/Infrastructure/DoctrineMapping'
                prefix: 'App\Notification\Domain\Entity'
                alias: Notification
            Template:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Template/Infrastructure/DoctrineMapping'
                prefix: 'App\Template\Domain\Entity'
                alias: Template