framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 1
            amqp_notification_creation:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: notification_creation
                        type: fanout
                    queues:
                        notification_creation: ~
            amqp_notification_dispatch:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: notification_dispatch
                        type: fanout
                    queues:
                        notification_dispatch: ~
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            App\Notification\Application\Model\CreateNotificationCommand: amqp_notification_creation
            App\Notification\Application\Model\DispatchNotificationCommand: amqp_notification_dispatch
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
