twig:
#    default_path: '%kernel.project_dir%/templates'
    paths:
        # directories are relative to the project root dir (but you
        # can also use absolute directories)
        '%kernel.project_dir%/src/Template/Application/Resources/templates': 'template'

when@test:
    twig:
        strict_variables: true
